version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tp3CloudComputing"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-heb7v2h3xrau"
s3_prefix = "tp3CloudComputing"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
